### ISSUE TITLE
Can i fork this and use it for my own purposes

### ISSUE THREAD

**Issue by RealYusufIsmail** [KhanhPham05/PatchouliDataGen#3]
I want to fork it and update it to 1.19.2. Is this fine

**Comment by KhanhPham05** [comment]
> I want to fork it and update it to 1.19.2. Is this fine

Yes it is totally fine !!! You can folk it and push a PR here or make your own mod version and you're free to publish it!!!

**Comment by RealYusufIsmail** [comment]
ok thx
